-- Baseline schema. Mirrors the JPA entity model.
-- For databases that already exist (built previously by ddl-auto=update),
-- Flyway is configured with baseline-on-migrate=true and baseline-version=1
-- so this script is recorded as already applied and is NOT executed.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255),
    description TEXT,
    owner_id BIGINT NOT NULL,
    active_version_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_documents_slug UNIQUE (slug),
    CONSTRAINT fk_documents_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    name VARCHAR(255),
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    author_id BIGINT NOT NULL,
    reviewer_id BIGINT,
    review_comment TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_document_version UNIQUE (document_id, version_number),
    CONSTRAINT fk_doc_version_document FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_doc_version_author   FOREIGN KEY (author_id)   REFERENCES users(id),
    CONSTRAINT fk_doc_version_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id)
);

ALTER TABLE documents
    ADD CONSTRAINT fk_documents_active_version
    FOREIGN KEY (active_version_id) REFERENCES document_versions(id);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_comments_version FOREIGN KEY (version_id) REFERENCES document_versions(id),
    CONSTRAINT fk_comments_author  FOREIGN KEY (author_id)  REFERENCES users(id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    details TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
);
